"""
CLI_COMMANDS.md ``generate-many`` scenarios (healthcare 1–21, industrial A–K).

Counts match the doc when ``use_doc_counts=True``; E2E tests default to minimal
counts (1 per type) for speed.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Mapping, Sequence

from fhir_gen.resolvers.dependency import MQL_SHIPPED_RESOURCES

MQL_84: tuple[str, ...] = MQL_SHIPPED_RESOURCES


@dataclass(frozen=True)
class GenerateManyScenario:
    """One healthcare / industrial data-generation scenario from CLI_COMMANDS."""

    id: str
    title: str
    seed: int
    resources: tuple[str, ...]
    counts: Mapping[str, int] = field(default_factory=dict)
    section: str = "healthcare"  # healthcare | industrial | bundle

    def db_name(self, prefix: str = "fhir_e2e_gen_") -> str:
        return f"{prefix}{self.id}"

    def resolve_counts(self, *, minimal: bool = True) -> dict[str, int]:
        if minimal and not self.counts:
            return {r: 1 for r in self.resources}
        if minimal and self.counts:
            return {r: min(3, self.counts.get(r, 1)) for r in self.resources}
        if self.counts:
            return dict(self.counts)
        return {r: 1 for r in self.resources}


def _hc(
    num: int,
    title: str,
    seed: int,
    resources: Sequence[str],
    **counts: int,
) -> GenerateManyScenario:
    return GenerateManyScenario(
        id=f"hc{num:02d}",
        title=title,
        seed=seed,
        resources=tuple(resources),
        counts=counts,
        section="healthcare",
    )


def _ind(
    slug: str,
    title: str,
    seed: int,
    resources: Sequence[str],
    **counts: int,
) -> GenerateManyScenario:
    return GenerateManyScenario(
        id=f"ind_{slug}",
        title=title,
        seed=seed,
        resources=tuple(resources),
        counts=counts,
        section="industrial",
    )


# ── Healthcare workflow scenarios (CLI_COMMANDS § Healthcare 1–21) ──────────

HEALTHCARE_SCENARIOS: tuple[GenerateManyScenario, ...] = (
    _hc(
        1,
        "Patient registration, MPI & person index",
        2001,
        ("Patient", "Person", "RelatedPerson", "Organization"),
        Patient=40,
        Person=10,
        RelatedPerson=35,
        Organization=4,
    ),
    _hc(
        2,
        "Provider directory, roles & network",
        2101,
        (
            "Organization",
            "Practitioner",
            "PractitionerRole",
            "OrganizationAffiliation",
            "Endpoint",
            "HealthcareService",
            "Location",
        ),
        Organization=6,
        Practitioner=20,
        PractitionerRole=25,
        OrganizationAffiliation=12,
        Endpoint=4,
        HealthcareService=8,
    ),
    _hc(
        3,
        "Facility, location & care episodes",
        2201,
        ("Organization", "Location", "EpisodeOfCare", "Account", "Patient"),
        Organization=4,
        Location=10,
        Patient=30,
        EpisodeOfCare=15,
        Account=20,
    ),
    _hc(
        4,
        "Scheduling & access management",
        2301,
        (
            "Patient",
            "Practitioner",
            "Organization",
            "Location",
            "Schedule",
            "Slot",
            "Appointment",
            "Encounter",
        ),
        Patient=25,
        Schedule=5,
        Slot=100,
        Appointment=90,
        Encounter=85,
    ),
    _hc(
        5,
        "Encounters, ward board & visit documents",
        2401,
        (
            "Patient",
            "Practitioner",
            "Encounter",
            "Composition",
            "DocumentReference",
            "Observation",
        ),
        Patient=20,
        Encounter=40,
        Composition=15,
        DocumentReference=20,
        Observation=80,
    ),
    _hc(
        6,
        "Problem list, allergies & clinical impressions",
        2501,
        (
            "Patient",
            "Encounter",
            "Condition",
            "AllergyIntolerance",
            "ClinicalImpression",
            "FamilyMemberHistory",
            "BodyStructure",
        ),
        Patient=30,
        Condition=50,
        AllergyIntolerance=18,
        ClinicalImpression=12,
        FamilyMemberHistory=10,
        BodyStructure=8,
    ),
    _hc(
        7,
        "Vitals, labs, imaging & specimens",
        2601,
        (
            "Patient",
            "Encounter",
            "Observation",
            "DiagnosticReport",
            "ImagingStudy",
            "Specimen",
            "Procedure",
        ),
        Patient=25,
        Observation=200,
        DiagnosticReport=35,
        ImagingStudy=15,
        Specimen=25,
        Procedure=20,
    ),
    _hc(
        8,
        "Medication management",
        2701,
        (
            "Patient",
            "Practitioner",
            "Medication",
            "MedicationRequest",
            "MedicationAdministration",
            "MedicationDispense",
            "MedicationStatement",
            "DetectedIssue",
        ),
        Patient=30,
        MedicationRequest=60,
        MedicationAdministration=50,
        MedicationDispense=35,
        MedicationStatement=40,
    ),
    _hc(
        9,
        "Orders, procedures & care coordination",
        2801,
        (
            "Patient",
            "Practitioner",
            "Encounter",
            "ServiceRequest",
            "Procedure",
            "DeviceRequest",
            "RequestOrchestration",
            "CarePlan",
            "CareTeam",
            "Goal",
            "Task",
        ),
        Patient=25,
        ServiceRequest=30,
        Procedure=22,
        DeviceRequest=12,
        RequestOrchestration=8,
        CarePlan=18,
        Task=35,
    ),
    _hc(
        10,
        "Devices, supplies & implants",
        2901,
        (
            "Patient",
            "Organization",
            "Device",
            "DeviceUsage",
            "DeviceDispense",
            "SupplyRequest",
            "SupplyDelivery",
            "BiologicallyDerivedProduct",
        ),
        Patient=20,
        Device=15,
        DeviceUsage=18,
        DeviceDispense=12,
        SupplyRequest=10,
        SupplyDelivery=10,
        BiologicallyDerivedProduct=6,
    ),
    _hc(
        11,
        "Immunizations & public health",
        3001,
        (
            "Patient",
            "Practitioner",
            "Location",
            "Appointment",
            "Immunization",
            "ImmunizationRecommendation",
            "Observation",
        ),
        Patient=50,
        Immunization=48,
        ImmunizationRecommendation=40,
    ),
    _hc(
        12,
        "Nutrition, vision & specialty orders",
        3101,
        (
            "Patient",
            "Practitioner",
            "Encounter",
            "NutritionOrder",
            "NutritionIntake",
            "VisionPrescription",
        ),
        Patient=20,
        NutritionOrder=12,
        NutritionIntake=25,
        VisionPrescription=10,
    ),
    _hc(
        13,
        "Eligibility, claims & revenue cycle",
        3201,
        (
            "Patient",
            "Organization",
            "Practitioner",
            "Coverage",
            "CoverageEligibilityRequest",
            "CoverageEligibilityResponse",
            "Claim",
            "ClaimResponse",
            "ExplanationOfBenefit",
            "ChargeItem",
            "ChargeItemDefinition",
            "Invoice",
            "PaymentNotice",
            "PaymentReconciliation",
        ),
        Patient=25,
        Coverage=30,
        Claim=22,
        ExplanationOfBenefit=15,
        ChargeItemDefinition=5,
        PaymentReconciliation=8,
    ),
    _hc(
        14,
        "Payer enrollment & plan catalog",
        3301,
        (
            "Organization",
            "Patient",
            "Coverage",
            "EnrollmentRequest",
            "EnrollmentResponse",
            "InsurancePlan",
        ),
        Organization=4,
        Patient=20,
        EnrollmentRequest=12,
        InsurancePlan=6,
    ),
    _hc(
        15,
        "Quality reporting (eCQM / HEDIS-style)",
        3401,
        ("Measure", "MeasureReport", "Patient", "Practitioner", "Organization"),
        Measure=5,
        MeasureReport=30,
        Patient=25,
    ),
    _hc(
        16,
        "Research, genomics & safety",
        3501,
        (
            "Organization",
            "ResearchStudy",
            "ResearchSubject",
            "Patient",
            "GenomicStudy",
            "AdverseEvent",
            "Group",
            "Condition",
        ),
        ResearchStudy=3,
        ResearchSubject=25,
        GenomicStudy=10,
        AdverseEvent=8,
    ),
    _hc(
        17,
        "Forms, PROs & patient-reported data",
        3601,
        (
            "Questionnaire",
            "QuestionnaireResponse",
            "Patient",
            "Practitioner",
            "Encounter",
        ),
        Questionnaire=4,
        QuestionnaireResponse=30,
        Patient=20,
    ),
    _hc(
        18,
        "Privacy, consent, contracts & communications",
        3701,
        (
            "Patient",
            "Organization",
            "Practitioner",
            "Consent",
            "Contract",
            "Communication",
            "Flag",
            "RiskAssessment",
        ),
        Patient=20,
        Consent=15,
        Contract=6,
        Communication=20,
    ),
    _hc(
        19,
        "Security audit & provenance",
        3801,
        (
            "Patient",
            "Practitioner",
            "Organization",
            "Encounter",
            "AuditEvent",
            "Provenance",
            "Basic",
        ),
        Patient=15,
        AuditEvent=40,
        Provenance=25,
        Basic=10,
    ),
    GenerateManyScenario(
        id="hc20",
        title="Full MQL sandbox (all 84 types)",
        seed=4000,
        resources=MQL_84,
        section="healthcare",
    ),
    _hc(
        21,
        "Regression dataset + QA export",
        5000,
        ("Patient", "Encounter", "Observation", "Condition"),
        Patient=10,
        Encounter=15,
        Observation=40,
        Condition=8,
    ),
)

# ── Industrial & enterprise (CLI_COMMANDS § Industrial A–K) ───────────────

INDUSTRIAL_SCENARIOS: tuple[GenerateManyScenario, ...] = (
    _ind(
        "hospital",
        "Hospital operations & capacity",
        6001,
        (
            "Organization",
            "Location",
            "Encounter",
            "Appointment",
            "Task",
            "Patient",
            "Practitioner",
        ),
        Encounter=80,
        Appointment=100,
        Task=50,
        Patient=60,
    ),
    _ind(
        "revcycle",
        "Revenue cycle & patient accounting",
        6101,
        (
            "Patient",
            "Organization",
            "Encounter",
            "ChargeItem",
            "Invoice",
            "Account",
            "Claim",
        ),
        ChargeItem=80,
        Invoice=15,
        Account=25,
        Claim=30,
    ),
    _ind(
        "payer",
        "Payer: eligibility → claim → EOB",
        6201,
        (
            "Patient",
            "Organization",
            "Coverage",
            "CoverageEligibilityRequest",
            "CoverageEligibilityResponse",
            "Claim",
            "ClaimResponse",
            "ExplanationOfBenefit",
            "PaymentNotice",
            "PaymentReconciliation",
        ),
        CoverageEligibilityRequest=15,
        CoverageEligibilityResponse=15,
        ExplanationOfBenefit=12,
        PaymentReconciliation=10,
    ),
    _ind(
        "pharmacy",
        "Pharmacy & medication safety",
        6301,
        (
            "Patient",
            "Medication",
            "MedicationRequest",
            "MedicationDispense",
            "DetectedIssue",
            "AdverseEvent",
        ),
        MedicationRequest=70,
        DetectedIssue=12,
        AdverseEvent=10,
    ),
    _ind(
        "device",
        "Medical device lifecycle",
        6401,
        (
            "Organization",
            "Device",
            "DeviceRequest",
            "DeviceUsage",
            "DeviceDispense",
            "Provenance",
            "Patient",
        ),
        Device=30,
        DeviceRequest=15,
        DeviceUsage=20,
        Provenance=15,
    ),
    _ind(
        "supply",
        "Supply chain & blood bank",
        6501,
        (
            "Organization",
            "Practitioner",
            "SupplyRequest",
            "SupplyDelivery",
            "BiologicallyDerivedProduct",
            "Specimen",
            "Patient",
        ),
        SupplyRequest=12,
        SupplyDelivery=12,
        BiologicallyDerivedProduct=8,
    ),
    _ind(
        "trials",
        "Clinical trials & RWE",
        6601,
        (
            "Organization",
            "ResearchStudy",
            "ResearchSubject",
            "Patient",
            "AdverseEvent",
            "GenomicStudy",
            "Condition",
        ),
        ResearchStudy=2,
        ResearchSubject=40,
        GenomicStudy=12,
    ),
    _ind(
        "quality",
        "Quality & regulatory reporting",
        6701,
        (
            "Measure",
            "MeasureReport",
            "AuditEvent",
            "Patient",
            "Organization",
        ),
        Measure=8,
        MeasureReport=50,
        AuditEvent=30,
    ),
    _ind(
        "interop",
        "Interoperability hub",
        6801,
        (
            "Organization",
            "OrganizationAffiliation",
            "Endpoint",
            "Provenance",
            "HealthcareService",
        ),
        OrganizationAffiliation=15,
        Endpoint=6,
        Provenance=20,
    ),
    _ind(
        "pophealth",
        "Population health & cohort analytics",
        6901,
        (
            "Patient",
            "Group",
            "Organization",
            "Observation",
            "Condition",
            "RiskAssessment",
            "ServiceRequest",
        ),
        Patient=120,
        Group=6,
        Observation=400,
        Condition=90,
        RiskAssessment=25,
    ),
    GenerateManyScenario(
        id="ind_full84",
        title="Load all 84 types for search/index demos",
        seed=7000,
        resources=MQL_84,
        section="industrial",
    ),
)

ALL_GENERATE_MANY_SCENARIOS: tuple[GenerateManyScenario, ...] = (
    *HEALTHCARE_SCENARIOS,
    *INDUSTRIAL_SCENARIOS,
)
