repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: ["--select", "F821"]
      - id: ruff-format
        stages: [manual]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml", "-lll", "-r", "src/kehrnel"]
        pass_filenames: false

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.3
    hooks:
      - id: gitleaks
        name: Detect secrets with Gitleaks
        description: Gitleaks has detected secrets in your changes
        entry: gitleaks protect --verbose --redact --staged
        language: golang
        pass_filenames: false
