# Commands for the OpenEHR API Server
FROM python:3.12-slim
WORKDIR /kerhnel
# COPY src/app/requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN pip install -e .[all]
CMD ["uvicorn", "kehrnel.api.app:app", "--host", "0.0.0.0", "--port", "8080"]
EXPOSE 8080
