FROM node:20-slim AS docs-builder
WORKDIR /docs
COPY docs/website/package*.json ./
RUN npm install
COPY docs/website/ ./
RUN npm run build

FROM python:3.13.13-slim
RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*
WORKDIR /kerhnel

COPY --from=docs-builder /docs/build docs/website/build

COPY . .
RUN pip install -e .[all]
ENV API_PORT=8080
ENV KEHRNEL_API_PORT=8080
ENV KEHRNEL_API_RELOAD=false
CMD ["kehrnel-api"]
EXPOSE 8080
