"""
Per-scenario ``fhir-mql search`` steps from CLI_COMMANDS.md (healthcare 1–19, 21; industrial A–J).

Keys match ``cli_scenarios_gen`` ids (``hc01``, ``ind_hospital``, …). Resources not listed here
get a type-specific fallback query when scenarios are built.
"""

from __future__ import annotations

SearchStep = tuple[str, str, tuple[str, ...]]


def _s(resource: str, query: str, *extra: str) -> SearchStep:
    return (resource, query, extra)


# Healthcare §1–19, §20 (compartment + spot checks), §21 — mirrors fhir-gen titles/ids
SCENARIO_SEARCHES: dict[str, tuple[SearchStep, ...]] = {
    "hc01": (
        _s("Patient", "active=true"),
        _s("Person", "name=Smith"),
        _s("RelatedPerson", "patient=p1"),
        _s("Organization", "active=true"),
    ),
    "hc02": (
        _s("Organization", "active=true"),
        _s("Practitioner", "active=true"),
        _s("PractitionerRole", "organization=org-1"),
        _s("OrganizationAffiliation", "primary-organization=org-1&active=true"),
        _s("Endpoint", "organization=org-1&status=active"),
        _s("HealthcareService", "organization=org-1"),
        _s("Location", "status=active"),
    ),
    "hc03": (
        _s("Organization", "name=Hospital&active=true"),
        _s("Location", "name=ER&status=active&organization=org-1"),
        _s("EpisodeOfCare", "patient=p1&status=active"),
        _s("Account", "patient=p1&status=active"),
        _s("Patient", "active=true"),
    ),
    "hc04": (
        _s("Patient", "active=true"),
        _s("Practitioner", "active=true"),
        _s("Organization", "active=true"),
        _s("Location", "status=active"),
        _s("Schedule", "active=true"),
        _s("Slot", "status=free"),
        _s("Appointment", "status=booked"),
        _s("Encounter", "status=in-progress"),
    ),
    "hc05": (
        _s("Patient", "active=true"),
        _s("Practitioner", "active=true"),
        _s("Encounter", "status=in-progress"),
        _s("Composition", "patient=p1&status=final"),
        _s("DocumentReference", "patient=p1&status=current"),
        _s("Observation", "status=final"),
    ),
    "hc06": (
        _s("Patient", "active=true"),
        _s("Encounter", "status=in-progress"),
        _s("Condition", "patient=p1&clinical-status=active"),
        _s("AllergyIntolerance", "patient=p1&clinical-status=active"),
        _s("ClinicalImpression", "patient=p1&status=completed"),
        _s("FamilyMemberHistory", "patient=p1"),
        _s("BodyStructure", "patient=p1"),
    ),
    "hc07": (
        _s("Patient", "active=true"),
        _s("Encounter", "status=in-progress"),
        _s("Observation", "patient=p1&category=vital-signs"),
        _s("DiagnosticReport", "patient=p1&status=final"),
        _s("ImagingStudy", "patient=p1&status=available"),
        _s("Specimen", "patient=p1&status=available"),
        _s("Procedure", "patient=p1&status=completed"),
    ),
    "hc08": (
        _s("Patient", "active=true"),
        _s("Practitioner", "active=true"),
        _s("Medication", "status=active"),
        _s("MedicationRequest", "patient=p1&status=active"),
        _s("MedicationAdministration", "patient=p1&status=completed"),
        _s("MedicationDispense", "patient=p1&status=completed"),
        _s("MedicationStatement", "patient=p1&status=recorded"),
        _s("DetectedIssue", "patient=p1&status=final"),
    ),
    "hc09": (
        _s("Patient", "active=true"),
        _s("Practitioner", "active=true"),
        _s("Encounter", "status=in-progress"),
        _s("ServiceRequest", "patient=p1&status=active"),
        _s("Procedure", "patient=p1&status=completed"),
        _s("DeviceRequest", "patient=p1&status=active"),
        _s("RequestOrchestration", "patient=p1&status=active"),
        _s("CarePlan", "patient=p1&status=active"),
        _s("CareTeam", "patient=p1&status=active"),
        _s("Goal", "patient=p1&lifecycle-status=active"),
        _s("Task", "patient=p1&status=in-progress"),
    ),
    "hc10": (
        _s("Patient", "active=true"),
        _s("Organization", "active=true"),
        _s("Device", "status=active"),
        _s("DeviceUsage", "patient=p1&status=active"),
        _s("DeviceDispense", "patient=p1&status=completed"),
        _s("SupplyRequest", "patient=p1&status=active"),
        _s("SupplyDelivery", "patient=p1&status=completed"),
        _s("BiologicallyDerivedProduct", "product-status=available"),
    ),
    "hc11": (
        _s("Patient", "active=true"),
        _s("Practitioner", "active=true"),
        _s("Location", "status=active"),
        _s("Appointment", "status=booked"),
        _s("Immunization", "patient=p1&status=completed"),
        _s("ImmunizationRecommendation", "patient=p1"),
        _s("Observation", "status=final"),
    ),
    "hc12": (
        _s("Patient", "active=true"),
        _s("Practitioner", "active=true"),
        _s("Encounter", "status=in-progress"),
        _s("NutritionOrder", "patient=p1&status=active"),
        _s("NutritionIntake", "patient=p1&status=completed"),
        _s("VisionPrescription", "patient=p1&status=active"),
    ),
    "hc13": (
        _s("Patient", "active=true"),
        _s("Organization", "active=true"),
        _s("Practitioner", "active=true"),
        _s("Coverage", "patient=p1&status=active"),
        _s("CoverageEligibilityRequest", "patient=p1&status=active"),
        _s("CoverageEligibilityResponse", "patient=p1&outcome=complete"),
        _s("Claim", "patient=p1&status=active"),
        _s("ClaimResponse", "patient=p1&outcome=complete"),
        _s("ExplanationOfBenefit", "patient=p1&status=active"),
        _s("ChargeItem", "patient=p1&status=billable"),
        _s("ChargeItemDefinition", "status=active"),
        _s("Invoice", "patient=p1&status=issued"),
        _s("PaymentNotice", "status=active"),
        _s("PaymentReconciliation", "status=active"),
    ),
    "hc14": (
        _s("Organization", "active=true"),
        _s("Patient", "active=true"),
        _s("Coverage", "status=active"),
        _s("EnrollmentRequest", "patient=p1&status=active"),
        _s("EnrollmentResponse", "status=active"),
        _s("InsurancePlan", "status=active"),
    ),
    "hc15": (
        _s("Measure", "status=active"),
        _s("MeasureReport", "patient=p1&status=complete"),
        _s("Patient", "active=true"),
        _s("Practitioner", "active=true"),
        _s("Organization", "active=true"),
    ),
    "hc16": (
        _s("Organization", "active=true"),
        _s("ResearchStudy", "status=active"),
        _s("ResearchSubject", "patient=p1&status=active"),
        _s("Patient", "active=true"),
        _s("GenomicStudy", "patient=p1&status=registered"),
        _s("AdverseEvent", "patient=p1&actuality=actual"),
        _s("Group", "type=person"),
        _s("Condition", "clinical-status=active"),
    ),
    "hc17": (
        _s("Questionnaire", "status=active"),
        _s("QuestionnaireResponse", "patient=p1&status=completed"),
        _s("Patient", "active=true"),
        _s("Practitioner", "active=true"),
        _s("Encounter", "status=in-progress"),
    ),
    "hc18": (
        _s("Patient", "active=true"),
        _s("Organization", "active=true"),
        _s("Practitioner", "active=true"),
        _s("Consent", "patient=p1&status=active"),
        _s("Contract", "patient=p1&status=executed"),
        _s("Communication", "patient=p1&status=completed"),
        _s("Flag", "patient=p1&status=active"),
        _s("RiskAssessment", "patient=p1"),
    ),
    "hc19": (
        _s("Patient", "active=true"),
        _s("Practitioner", "active=true"),
        _s("Organization", "active=true"),
        _s("Encounter", "status=in-progress"),
        _s("AuditEvent", "patient=p1&action=R"),
        _s("Provenance", "patient=p1&activity=CREATE"),
        _s("Basic", "patient=p1"),
    ),
    "hc20": (
        _s("Patient", "active=true"),
        _s("Observation", "status=final&code=8480-6", "--compartment-type", "Patient", "--compartment-id", "p1"),
        _s("MedicationRequest", "status=active", "--compartment-type", "Patient", "--compartment-id", "p1"),
        _s("Encounter", "status=finished", "--compartment-type", "Patient", "--compartment-id", "p1"),
        _s("MeasureReport", "status=complete"),
    ),
    "hc21": (
        _s("Patient", "active=true"),
        _s("Encounter", "status=finished"),
        _s("Observation", "status=final"),
        _s("Condition", "clinical-status=active"),
    ),
    "ind_hospital": (
        _s("Organization", "active=true"),
        _s("Location", "operational-status=O"),
        _s("Encounter", "status=in-progress"),
        _s("Appointment", "status=booked"),
        _s("Task", "status=in-progress"),
        _s("Patient", "active=true"),
        _s("Practitioner", "active=true"),
    ),
    "ind_revcycle": (
        _s("Patient", "active=true"),
        _s("Organization", "active=true"),
        _s("Encounter", "status=in-progress"),
        _s("ChargeItem", "status=billable"),
        _s("Invoice", "status=issued"),
        _s("Account", "status=active"),
        _s("Claim", "status=active"),
    ),
    "ind_payer": (
        _s("Patient", "active=true"),
        _s("Organization", "active=true"),
        _s("Coverage", "status=active"),
        _s("CoverageEligibilityRequest", "status=active"),
        _s("CoverageEligibilityResponse", "outcome=complete"),
        _s("Claim", "status=active"),
        _s("ClaimResponse", "outcome=complete"),
        _s("ExplanationOfBenefit", "status=active"),
        _s("PaymentNotice", "status=active"),
        _s("PaymentReconciliation", "status=active"),
    ),
    "ind_pharmacy": (
        _s("Patient", "active=true"),
        _s("Medication", "status=active"),
        _s("MedicationRequest", "status=active"),
        _s("MedicationDispense", "status=completed"),
        _s("DetectedIssue", "status=final"),
        _s("AdverseEvent", "actuality=actual"),
    ),
    "ind_device": (
        _s("Organization", "active=true"),
        _s("Device", "status=active"),
        _s("DeviceRequest", "status=active"),
        _s("DeviceUsage", "status=active"),
        _s("DeviceDispense", "status=completed"),
        _s("Provenance", "activity=UPDATE"),
        _s("Patient", "active=true"),
    ),
    "ind_supply": (
        _s("Organization", "active=true"),
        _s("Practitioner", "active=true"),
        _s("SupplyRequest", "status=active"),
        _s("SupplyDelivery", "status=completed"),
        _s("BiologicallyDerivedProduct", "product-status=available"),
        _s("Specimen", "status=available"),
        _s("Patient", "active=true"),
    ),
    "ind_trials": (
        _s("Organization", "active=true"),
        _s("ResearchStudy", "status=active"),
        _s("ResearchSubject", "status=active"),
        _s("Patient", "active=true"),
        _s("AdverseEvent", "actuality=actual"),
        _s("GenomicStudy", "status=registered"),
        _s("Condition", "clinical-status=active"),
    ),
    "ind_quality": (
        _s("Measure", "status=active"),
        _s("MeasureReport", "status=complete"),
        _s("AuditEvent", "action=R"),
        _s("Patient", "active=true"),
        _s("Organization", "active=true"),
    ),
    "ind_interop": (
        _s("Organization", "active=true"),
        _s("OrganizationAffiliation", "active=true"),
        _s("Endpoint", "status=active"),
        _s("Provenance", "activity=CREATE"),
        _s("HealthcareService", "organization=org-1"),
    ),
    "ind_pophealth": (
        _s("Patient", "active=true"),
        _s("Group", "type=person"),
        _s("Organization", "active=true"),
        _s("Observation", "status=final"),
        _s("Condition", "clinical-status=active"),
        _s("RiskAssessment", "method=clinical"),
        _s("ServiceRequest", "status=active"),
    ),
    "ind_full84": (
        _s("Patient", "active=true"),
    ),
}
