"""MongoDB persistence adapter interfaces."""
from __future__ import annotations

from typing import Any, Dict, Iterable, List, Protocol


class StorageAdapter(Protocol):
    async def insert_one(self, collection: str, doc: Dict[str, Any]) -> Any: ...
    async def insert_many(self, collection: str, docs: Iterable[Dict[str, Any]]) -> Any: ...
    async def find_one(self, collection: str, flt: Dict[str, Any], projection: Dict[str, Any] | None = None) -> Dict[str, Any] | None: ...
    async def aggregate(self, collection: str, pipeline: List[Dict[str, Any]], allow_disk_use: bool = True) -> List[Dict[str, Any]]: ...
    async def delete_many(self, collection: str, flt: Dict[str, Any]) -> Any: ...


class IndexAdminAdapter(Protocol):
    async def ensure_collection(self, name: str) -> None: ...
    async def ensure_indexes(self, collection: str, index_specs: List[Dict[str, Any]]) -> Dict[str, Any]: ...


class TextSearchAdapter(Protocol):
    async def ensure_search_index(self, collection: str, index_name: str, definition: Dict[str, Any]) -> Dict[str, Any]: ...
    async def list_search_indexes(self, collection: str) -> List[Dict[str, Any]]: ...
