#!/usr/bin/env python3
"""Drop E2E MongoDB databases and optional fhir-mql search result artifacts."""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MQL_RESULTS_DIR = REPO_ROOT.parent / "fhir-search-to-mql" / "tests" / "e2e" / "results"

DEFAULT_URI = os.environ.get("E2E_MONGODB_URI", "mongodb://localhost:27017/")
DEFAULT_PREFIX = os.environ.get("E2E_DB_PREFIX", "fhir_e2e_")


def _drop_databases(uri: str, prefix: str, *, dry_run: bool) -> list[str]:
    from pymongo import MongoClient

    client = MongoClient(uri, serverSelectionTimeoutMS=5000)
    client.server_info()
    names = sorted(n for n in client.list_database_names() if n.startswith(prefix))
    for name in names:
        if dry_run:
            print(f"would drop database: {name}")
        else:
            client.drop_database(name)
            print(f"dropped database: {name}")
    client.close()
    return names


def _clear_search_results(results_dir: Path, *, dry_run: bool) -> list[str]:
    if not results_dir.is_dir():
        return []
    removed = [p.name for p in results_dir.iterdir() if p.is_dir()]
    if dry_run:
        for name in removed:
            print(f"would remove results: {results_dir / name}")
    else:
        import shutil

        shutil.rmtree(results_dir)
        results_dir.mkdir(parents=True, exist_ok=True)
        (results_dir / ".gitignore").write_text(
            "# Generated by E2E search tests\n*\n!.gitignore\n",
            encoding="utf-8",
        )
        print(f"cleared search results: {results_dir} ({len(removed)} scenario folders)")
    return removed


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Drop E2E MongoDB databases and fhir-mql search result JSON files",
    )
    parser.add_argument("--uri", default=DEFAULT_URI)
    parser.add_argument(
        "--prefix",
        default=DEFAULT_PREFIX,
        help="Drop databases whose names start with this prefix (default: fhir_e2e_)",
    )
    parser.add_argument(
        "--results-dir",
        type=Path,
        default=MQL_RESULTS_DIR,
        help="fhir-search-to-mql tests/e2e/results directory to clear",
    )
    parser.add_argument(
        "--no-clear-results",
        action="store_true",
        help="Only drop MongoDB databases, keep search_results.json files",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="List what would be removed",
    )
    args = parser.parse_args()

    try:
        from pymongo import MongoClient  # noqa: F401
    except ImportError:
        print("Install pymongo", file=sys.stderr)
        return 1

    db_names = _drop_databases(args.uri, args.prefix, dry_run=args.dry_run)
    if not db_names:
        print(f"No databases matching prefix {args.prefix!r}")

    if not args.no_clear_results:
        if args.results_dir.exists() or not args.dry_run:
            _clear_search_results(args.results_dir, dry_run=args.dry_run)
        else:
            print(f"No search results dir at {args.results_dir}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
