"""
Resolve FHIR schema + search-package data directories.

Data lives outside the Python package at repo root ``schema/`` (or ``FHIR_SCHEMA_ROOT``):

  schema/
    fhir.schema.v5.json
    fhir.schema.v6.json
    hl7.fhir.r5.search/package/
    hl7.fhir.r6.search/package/
    indexes/                    # generated by build_indexes
"""

from __future__ import annotations

import os
from functools import lru_cache
from pathlib import Path

_PKG_DIR = Path(__file__).resolve().parent


def _find_repo_root() -> Path:
    for candidate in (_PKG_DIR, *_PKG_DIR.parents):
        if (candidate / "schema" / "fhir.schema.v5.json").is_file():
            return candidate
    raise FileNotFoundError(
        "Could not locate repo schema/ folder (fhir.schema.v5.json). "
        "Set FHIR_SCHEMA_ROOT to your schema data directory."
    )


@lru_cache(maxsize=1)
def repo_root() -> Path:
    return _find_repo_root()


@lru_cache(maxsize=1)
def schema_data_root() -> Path:
    """Root folder for FHIR JSON Schema + HL7 search packages + indexes."""
    env = os.environ.get("FHIR_SCHEMA_ROOT")
    if env:
        path = Path(env).expanduser().resolve()
        if not path.is_dir():
            raise FileNotFoundError(f"FHIR_SCHEMA_ROOT is not a directory: {path}")
        return path

    default = repo_root() / "schema"
    if not default.is_dir():
        raise FileNotFoundError(
            f"Schema data directory not found: {default}\n"
            "Place FHIR schema/search assets under <repo>/schema/ or set FHIR_SCHEMA_ROOT."
        )
    return default


def indexes_dir() -> Path:
    return schema_data_root() / "indexes"


def schema_json_path(version: str) -> Path:
    v = version.upper().strip()
    if v in ("R5", "5", "V5"):
        return schema_data_root() / "fhir.schema.v5.json"
    if v in ("R6", "6", "V6"):
        return schema_data_root() / "fhir.schema.v6.json"
    raise ValueError(f"Unknown version {version!r}; use R5 or R6")


def search_package_dir(version: str) -> Path:
    suffix = "r5" if version.upper().startswith("R5") else "r6"
    return schema_data_root() / f"hl7.fhir.{suffix}.search" / "package"


def configs_dir() -> Path:
    return _PKG_DIR.parent / "configs"
